# Generated by Django 5.1.6 on 2025-02-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название корпуса')),
                ('additional_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительное название корпуса')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпусы',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('code_mo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код МО в СМО')),
                ('oid_mo', models.CharField(max_length=50, verbose_name='OID МО')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения')),
                ('additional_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительное название отделения')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификатор из внешней системы')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='MOConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField(blank=True, null=True, verbose_name='Конфигурация')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Выбранная МО')),
            ],
            options={
                'verbose_name': 'Конфигурация МО',
                'verbose_name_plural': 'Конфигурации МО',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='organization.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='RelatedDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения')),
                ('source', models.CharField(max_length=255, verbose_name='Источник')),
                ('configuration', models.JSONField(blank=True, null=True, verbose_name='Конфигурация')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oms_departments', to='organization.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Отделение: связанное',
                'verbose_name_plural': 'Отделения: связанные',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код участка')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название участка')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='Дата введения участка')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Дата закрытия участка')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organization.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
    ]
