# Generated by Django 5.1.6 on 2025-02-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kadry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название корпуса')),
                ('additional_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительное название корпуса')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпусы',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('code_mo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код МО в СМО')),
                ('oid_mo', models.CharField(max_length=50, verbose_name='OID МО')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Организацию',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название внешней системы')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Внешняя система',
                'verbose_name_plural': 'Внешние системы',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения')),
                ('additional_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительное название отделения')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='organization.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='ActiveOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Главная организация')),
            ],
            options={
                'verbose_name': 'Активную организацию',
                'verbose_name_plural': 'Активная организация',
            },
        ),
        migrations.CreateModel(
            name='RelatedDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_department_name', models.CharField(max_length=255, verbose_name='Название отделения во внешней системе')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_departments', to='organization.department', verbose_name='Отделение')),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.sourcesystem', verbose_name='Внешняя система')),
            ],
            options={
                'verbose_name': 'Связь с внешним отделением',
                'verbose_name_plural': 'Связи с внешними отделениями',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код участка')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название участка')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='Дата введения участка')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Дата закрытия участка')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='organization.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='StationDoctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Дата начала')),
                ('removal_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.employee', verbose_name='Врач')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='organization.station', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Назначение врача на участок',
                'verbose_name_plural': 'Назначения врачей на участок',
            },
        ),
    ]
