# Generated by Django 5.1.6 on 2025-02-11 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код должности')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код профиля')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование профиля')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Ставка')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
            },
        ),
        migrations.CreateModel(
            name='DoctorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Код врача')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_codes', to='kadry.appointment', verbose_name='Назначение врача')),
            ],
            options={
                'verbose_name': 'Код врача',
                'verbose_name_plural': 'Коды врачей',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Табельный номер')),
                ('physical_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person.physicalperson', verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='kadry.employee', verbose_name='Сотрудник'),
        ),
        migrations.CreateModel(
            name='MaternityLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('planned_end_date', models.DateField(verbose_name='Планируемая дата окончания')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternity_leaves', to='kadry.appointment', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Декрет',
                'verbose_name_plural': 'Декреты',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kadry.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kadry.profile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kadry.specialty', verbose_name='Специальность'),
        ),
    ]
