# Generated by Django 5.1.6 on 2025-02-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kadry', '0001_initial'),
        ('organization', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='Отделение'),
        ),
        migrations.AddField(
            model_name='doctorcode',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_codes', to='kadry.appointment', verbose_name='Назначение врача'),
        ),
        migrations.AddField(
            model_name='employee',
            name='physical_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person.physicalperson', verbose_name='Физическое лицо'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='kadry.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='maternityleave',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternity_leaves', to='kadry.appointment', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kadry.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kadry.profile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kadry.specialty', verbose_name='Специальность'),
        ),
    ]
