# Generated by Django 5.1.6 on 2025-02-11 13:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(db_column='Код', unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страховая компания',
                'verbose_name_plural': 'Страховые компании',
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp', models.CharField(max_length=16, unique=True, verbose_name='ЕНП')),
                ('start_date', models.DateField(verbose_name='Дата_начала_страхования')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата_окончания_страхования')),
                ('insurance', models.ForeignKey(db_column='Код_СМО', on_delete=django.db.models.deletion.PROTECT, to='person.insurance', verbose_name='Страховая организация')),
            ],
            options={
                'verbose_name': 'Полис',
                'verbose_name_plural': 'Полисы',
            },
        ),
        migrations.CreateModel(
            name='PhysicalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата_рождения')),
                ('gender', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=1, verbose_name='Пол')),
                ('snils', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='СНИЛС должен состоять из 11 цифр', regex='^[0-9]{11}$')], verbose_name='СНИЛС')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен начинаться с 8 и содержать 11 цифр', regex='^8[0-9]{10}$')], verbose_name='Телефон')),
                ('telegram', models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм')),
                ('policy', models.ForeignKey(blank=True, db_column='id_полиса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.insurancepolicy', verbose_name='Полис')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['enp'], name='person_insu_enp_f979b5_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalperson',
            index=models.Index(fields=['last_name', 'birth_date', 'snils', 'phone'], name='person_phys_last_na_f2f54b_idx'),
        ),
    ]
