# Generated by Django 5.1.6 on 2025-02-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalperson',
            name='policy',
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='physical_persons', to='person.insurancepolicy', verbose_name='Полисы'),
        ),
    ]
